baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "The DIY Blogger"
theme = "massively"
disqusShortname = "thediyblogger"
googleAnalytics = "UA-132745738-2"
enableRobotsTXT = true

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"


# set below parameter to define a favicon
[params]
  favicon = "/favicon.png"
  author = "Amit Gandhi"
	site_description = "Your guide to exponentially increasing your blog traffic."
	description = "Your guide to exponentially increasing your blog traffic."
  pinkarma_api = "http://localhost:8001"
  pinterest_client_id = "5034711914840639840"
  pinterest_scope = "read_public, write_public"
  google_client_id = "587187345724-mhc7fi3v56n0507muonqq0ca6qo9omjo.apps.googleusercontent.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "blog"
     pagesize = "10"
     featuredpost = "false"

[permalinks]
  blog = "/blog/:title/"

[taxonomies]
  category = "categories"

[languages]
[languages.en]
  languageName = "English"

