baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "The DIY Blogger"
theme = "massively"
disqusShortname = "thediyblogger"
googleAnalytics = "UA-132745738-2"

# set below parameter to define a favicon
[params]
  favicon = "/favicon.png"
  author = "Amit Gandhi"
	site_description = "Your guide to exponentially increasing your blog traffic."
	description = "Your guide to exponentially increasing your blog traffic."
  pinkarma_api = "http://127.0.0.1:8001"
  pinterest_client_id = "5034711914840639840"
  pinterest_scope = "read_public, write_public"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "blog"
     pagesize = "10"
     featuredpost = "false"

[permalinks]
  blog = "/blog/:title/"

[taxonomies]
  category = "categories"

[languages]
[languages.en]
  languageName = "English"

